import fs from "fs-extra";
import inquirer from "inquirer";
import { format } from "prettier";
import { spawnSync } from "child_process";

/**
 * @param {string} oldVersion
 * @returns {Promise<string>}
 */
const checkVersion = async (oldVersion) => {
  if (oldVersion.includes("beta")) {
    const V = oldVersion.split("-beta.")[0];
    const B = Number(oldVersion.split("-beta.")[1]);
    const update = `${V}-beta.${B + 1}`;
    const publish = `${V}`;
    const { option } = await inquirer.prompt([
      {
        type: "list",
        name: "option",
        message: `current version ${
          oldVersion ?? "undefined"
        }, please select update level`,
        choices: [
          { value: "update", name: `update beta(${update})` },
          { value: "publish", name: `finish beta(${publish})` },
          { value: "old", name: `maintain(${oldVersion})` },
        ],
        default: "update",
      },
    ]);
    if (option === "update") {
      return update;
    } else if (option === "publish") {
      return publish;
    } else {
      return oldVersion;
    }
  } else {
    const [H, N, S] = oldVersion.split(".").map((item) => Number(item));
    const B = "-beta.0";
    const small = `${H}.${N}.${S + 1}${B}`;
    const normal = `${H}.${N + 1}.0${B}`;
    const huge = `${H + 1}.0.0${B}`;
    const { option } = await inquirer.prompt([
      {
        type: "list",
        name: "option",
        message: `current version ${
          oldVersion ?? "undefined"
        }, please select update level`,
        choices: [
          { value: "small", name: `simple beta(${small})` },
          { value: "normal", name: `normal beta(${normal})` },
          { value: "huge", name: `upgrade beta(${huge})` },
          { value: "old", name: `maintain(${oldVersion})` },
        ],
      },
    ]);
    if (option === "small") {
      return small;
    } else if (option === "normal") {
      return normal;
    } else if (option === "huge") {
      return huge;
    } else {
      return oldVersion;
    }
  }
};

async function changeVersion(version) {
  const packageFile = await fs.readJSON("./package.json");
  const versionFilePath = "./src/config.ts";
  const warningStr =
    "/** Don't modify this file which is generated by cli */\n";
  const configFileStr = (await fs.readFile(versionFilePath, "utf-8"))
    .replace(`${warningStr}*`, "")
    .replace("export default ", "")
    .replace(/\/\*\*.*\*\/\n*/g, "");
  const configFile = JSON.parse(configFileStr);
  packageFile.version = version;
  configFile.version = version;
  const str = format(
    `${warningStr}export default ${JSON.stringify(configFile, null, 2)}`,
    {
      singleQuote: false,
      trailingComma: "none",
      semi: false,
      quoteProps: "preserve",
      parser: "babel",
    }
  );
  await Promise.all([
    fs.writeJson("./package.json", packageFile, {
      spaces: 2,
    }),
    fs.writeFile(versionFilePath, str),
  ]);
  spawnSync("npm run build", {
    stdio: "inherit",
    shell: true,
  });
  console.log(`config, package.json now ${version}`);
}

async function getVersion() {
  const packageFile = await fs.readJSON("./package.json");
  /** @type { string } */
  return packageFile.version;
}

export async function customizeVersion() {
  const oldVerion = await getVersion();
  const { version } = await inquirer.prompt([
    {
      type: "input",
      name: "version",
      message: `current version ${
        oldVerion ?? "undefined"
      }, input target version`,
      default: "oldVerion",
    },
  ]);
  await changeVersion(version);
}

export default checkVersion;
